spring.application.name=barbex
server.port=8080

# Configuracion de MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/barbex_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Costa_Rica&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Burbuja1407}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Formato de fechas y horas
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.time=HH:mm

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
